/* =========================================================
   FIFTY BAR VAPE — Complete Product Catalog v3
   All products correctly mapped to categories
   ========================================================= */

const FBV = {

  /* ── STORE RULES ── */
  rules: {
    minOrder: 150,          // $150 minimum order
    freeShipping: 250,      // Free shipping over $250
    shippingCost: 15,       // Flat shipping under $250
    cryptoDiscount: 0.10,   // 10% off for crypto payment
    taxRate: 0,             // No tax (vape products - state handled)
  },

  /* ── CATEGORIES ── */
  categories: [
    { id:'original-series',  label:'Original Series',          puffs:'6,500',  price:18.99, sbsImg:'sbs-original-series.webp',  bg:'#1A0E08', emoji:'🟤',
      desc:'The flagship Fifty Bar Original Series — the device that started it all. Built and filled in the USA with bold, authentic flavor profiles and 6,500 puffs of American-made e-liquid.' },
    { id:'white-series',     label:'White Series',             puffs:'6,500',  price:18.99, sbsImg:'sbs-white-series.webp',      bg:'#DEDEDE', emoji:'⚪',
      desc:'The Fifty Bar White Series brings clean, vibrant fruit and candy blends to the iconic white device. 6,500 puffs of crisp, refreshing American-made flavor.' },
    { id:'black-series',     label:'Black Series',             puffs:'20,000', price:24.99, sbsImg:'sbs-black-series.webp',      bg:'#0A0A0A', emoji:'⚫',
      desc:'The Fifty Bar Black Series delivers 20,000 puffs of bold, indulgent flavors. Featuring dessert, tobacco, and cereal profiles — all American made with the latest mesh coil tech.' },
    { id:'fruitia',          label:'Fifty Bar × Fruitia 20K', puffs:'20,000', price:24.99, sbsImg:'sbs-fruitia.webp',           bg:'#0E0E0E', emoji:'🍓',
      desc:'Two American icons. Fruitia and Fifty Bar unite for a 20,000-puff high-performance collab packed with Fruitia\'s signature fruit candy blends.' },
    { id:'humble',           label:'Fifty Bar × Humble',       puffs:'6,500',  price:18.99, sbsImg:'sbs-humble.webp',            bg:'#0A0A0A', emoji:'🦅',
      desc:'Humble and Fifty Bar. Two American originals drop a red, white, and blue collab — 10 iconic Humble flavors in the Fifty Bar device.' },
    { id:'hidden-hills',     label:'Fifty Bar × Hidden Hills', puffs:'6,500',  price:18.99, sbsImg:'sbs-hidden-hills.webp',      bg:'#F0E8DC', emoji:'🌿',
      desc:'Hidden Hills Club meets Fifty Bar. Elevated, premium flavor profiles in the iconic Fifty Bar device — bold fruit, icy, and tobacco blends in 6,500-puff format.' },
    { id:'midnight-series',  label:'Midnight Series',          puffs:'20,000', price:24.99, sbsImg:'sbs-midnight-series.webp',   bg:'#111118', emoji:'🌙',
      desc:'Introducing the Fifty Bar Midnight Series — 20,000 puffs of bold fruit flavors with Always Active Boost Mode, Dual Parallel Mesh Coil, and a 900mAh rechargeable battery.' },
  ],

  /* ── DEVICE SPECS per series ── */
  specs: {
    standard: { puffs:'6,500', battery:'650mAh Rechargeable', coil:'Mesh Coil', nicotine:'5% (50mg)', capacity:'18mL', charging:'USB-C' },
    twentyk:  { puffs:'20,000', battery:'900mAh Rechargeable (Grade A)', coil:'Dual Parallel Mesh Coil', nicotine:'5% (50mg)', capacity:'28mL', charging:'USB-C', boost:'Always Active Boost Mode', airflow:'3-Level Adjustable Airflow', display:'Visual Battery & E-Liquid Display' },
  },

  /* ── PRODUCTS ── */
  products: [

    /* ── ORIGINAL SERIES (6,500 puffs) ── */
    { id:'aloe-grapple-watermelon',     cat:'original-series', name:'Aloe Grapple Watermelon',    img:'original-series/aloe-grapple-watermelon.webp',    price:18.99, puffs:'6,500', badge:null,
      desc:'A soothing fusion of cool aloe vera, tart green apple, and juicy fresh watermelon. Smooth from first puff to last, this American-made flavor delivers a hydrating, layered fruit experience that\'s impossible to put down.',
      tags:['fruit','aloe','watermelon'] },
    { id:'aloe-kiwi-strawberry',        cat:'original-series', name:'Aloe Kiwi Strawberry',       img:'original-series/aloe-kiwi-strawberry.webp',       price:18.99, puffs:'6,500', badge:'Popular',
      desc:'Sweet ripe strawberries and tropical kiwi float on a bed of smooth aloe vera in this fan-favorite Original Series flavor. Bright, refreshing, and perfectly balanced — a crowd-pleaser for any palette.',
      tags:['fruit','kiwi','strawberry'] },
    { id:'blue-razzle-ice',             cat:'original-series', name:'Blue Razzle Ice',             img:'original-series/blue-razzle-ice.webp',            price:18.99, puffs:'6,500', badge:null,
      desc:'Tangy blue raspberry candy meets an arctic ice blast for an intensely cool vaping experience. Sharp fruit on the inhale, clean frozen finish on the exhale — pure razzle-dazzle in every puff.',
      tags:['fruit','ice','berry'] },
    { id:'blueberry-cereal-donut-milk-os', cat:'original-series', name:'Blueberry Cereal Donut Milk', img:'original-series/blueberry-cereal-donut-milk.webp', price:18.99, puffs:'6,500', badge:'Bestseller',
      desc:'Wake up to a bowl of sweet blueberry cereal, soft glazed donut, and creamy cold milk — all in one puff. This Original Series icon delivers layered bakery-fruit complexity that keeps you coming back all day.',
      tags:['dessert','cereal','blueberry'] },
    { id:'cinnamon-funnel-cake-os',     cat:'original-series', name:'Cinnamon Funnel Cake',       img:'original-series/cinnamon-funnel-cake.webp',       price:18.99, puffs:'6,500', badge:'🔥 Hot',
      desc:'Freshly fried funnel cake dusted with warm cinnamon sugar, straight from the fairground. Sweet, doughy, and spiced — this is comfort vaping at its absolute finest. One of the most unique flavors in the Original Series lineup.',
      tags:['dessert','cinnamon','pastry'] },
    { id:'diamond-peach-ice',           cat:'original-series', name:'Diamond Peach Ice',           img:'original-series/diamond-peach-ice.webp',          price:18.99, puffs:'6,500', badge:null,
      desc:'Premium Georgia peach at peak ripeness, crushed over a diamond-grade ice blend for maximum frost. Sweet stone fruit inhale, refreshingly cold exhale — flawless execution in the Original Series tradition.',
      tags:['fruit','peach','ice'] },
    { id:'juicy-mango-melon-ice',       cat:'original-series', name:'Juicy Mango Melon Ice',      img:'original-series/juicy-mango-melon-ice.webp',      price:18.99, puffs:'6,500', badge:null,
      desc:'Tropical Alphonso mango and sweet honeydew melon join forces for a juicy tropical duo, finished with a clean icy exhale. A perfect summer flavor built to USA standards.',
      tags:['fruit','mango','melon','ice'] },
    { id:'kyoho-grape-jelly',           cat:'original-series', name:'Kyoho Grape Jelly',           img:'original-series/kyoho-grape-jelly.webp',          price:18.99, puffs:'6,500', badge:null,
      desc:'Authentic Japanese Kyoho grape — dark, sweet, and deeply rich — captured as a smooth grape jelly vape. Unique and bold, this is not your average grape. A sophisticated pick for the Original Series collector.',
      tags:['fruit','grape'] },
    { id:'mint-os',                     cat:'original-series', name:'Mint',                        img:'original-series/mint.webp',                       price:18.99, puffs:'6,500', badge:null,
      desc:'Pure American peppermint — clean, icy, and unapologetically fresh. No additives, no frills — just the clearest mint experience available in a USA-made disposable. The go-to palate cleanser between flavors.',
      tags:['mint','ice'] },
    { id:'pacific-cooler',             cat:'original-series', name:'Pacific Cooler',              img:'original-series/pacifc-cooler.webp',              price:18.99, puffs:'6,500', badge:null,
      desc:'Inspired by the classic juice blend, Pacific Cooler brings tropical punch fruit — citrus, grape, and cherry — together in a cool, refreshing wave. Easy drinking, always smooth, endlessly satisfying.',
      tags:['fruit','tropical','citrus'] },
    { id:'pink-squares',               cat:'original-series', name:'Pink Squares',                img:'original-series/pink-squares.webp',               price:18.99, puffs:'6,500', badge:null,
      desc:'Sweet pink candy squares — the nostalgia of old-fashioned chewy candy packed into every puff. Bright, sugary, and uniquely playful. A fan-favorite among those who love bold candy profiles.',
      tags:['candy','sweet'] },
    { id:'tobaccocino',                 cat:'original-series', name:'Tobaccocino',                 img:'original-series/tobaccocino.webp',                price:18.99, puffs:'6,500', badge:null,
      desc:'Smooth American tobacco meets rich espresso in this sophisticated Original Series blend. The perfect morning vape — bold tobacco base, creamy coffee finish, with just a hint of sweetness. Premium craftsmanship from start to finish.',
      tags:['tobacco','coffee'] },
    { id:'triple-watermelon',           cat:'original-series', name:'Triple Watermelon',           img:'original-series/triple-watermelon.webp',          price:18.99, puffs:'6,500', badge:'Popular',
      desc:'Three layers of watermelon — fresh rind, sweet heart, and icy cold blast — stacked into one monumental flavor experience. The ultimate watermelon vape for enthusiasts who can\'t get enough of the summer staple.',
      tags:['fruit','watermelon','ice'] },
    { id:'vanilla-custard-os',          cat:'original-series', name:'Vanilla Custard',             img:'original-series/vanilla-custard.webp',            price:18.99, puffs:'6,500', badge:'Bestseller',
      desc:'Rich, velvety vanilla custard — smooth, creamy, and perfectly sweet. Made with American-sourced vanilla flavor, this is one of the most beloved Fifty Bar Original Series flavors. Dessert vaping perfected.',
      tags:['dessert','vanilla','cream'] },

    /* ── WHITE SERIES (6,500 puffs) ── */
    { id:'baja-mango',                  cat:'white-series', name:'Baja Mango',                  img:'white-series/baja-mango.webp',                  price:18.99, puffs:'6,500', badge:null,
      desc:'Sun-ripened mango fresh off the Baja coast — sweet, tropical, and slightly tangy. This White Series staple delivers authentic mango flavor with every puff. Light, clean, and consistently delicious.',
      tags:['fruit','mango','tropical'] },
    { id:'clear',                       cat:'white-series', name:'Clear',                       img:'white-series/clear.webp',                       price:18.99, puffs:'6,500', badge:null,
      desc:'Pure, clean vapor with no added flavor — just smooth, unflavored vaping with American-made e-liquid. Perfect for the minimalist vaper or as a palate reset between flavors. Deceptively simple, impeccably made.',
      tags:['unflavored'] },
    { id:'fresh-mango-lychee',          cat:'white-series', name:'Fresh Mango Lychee',          img:'white-series/fresh-mango-lychee.webp',          price:18.99, puffs:'6,500', badge:'Popular',
      desc:'Tropical ripe mango meets delicately floral lychee in this beautifully balanced White Series blend. Light, exotic, and perfectly sweet — this is the ultimate warm-weather flavor.',
      tags:['fruit','mango','lychee','tropical'] },
    { id:'frozen-apple',                cat:'white-series', name:'Frozen Apple',                img:'white-series/frozen-apple.webp',                price:18.99, puffs:'6,500', badge:null,
      desc:'Crisp Granny Smith apple, frozen at peak tartness for a shockingly fresh vaping experience. The bite of green apple with an arctic exhale — clean, sharp, and deeply satisfying.',
      tags:['fruit','apple','ice'] },
    { id:'frozen-orange-mango-pear',    cat:'white-series', name:'Frozen Orange Mango Pear',   img:'white-series/frozen-orange-mango-pear.webp',    price:18.99, puffs:'6,500', badge:null,
      desc:'A frozen tropical trio — bright citrus orange, sweet mango, and juicy ripe pear — blasted together for a multi-layered icy fruit experience. Refreshing, complex, and endlessly drinkable.',
      tags:['fruit','tropical','ice'] },
    { id:'frozen-watermelon',           cat:'white-series', name:'Frozen Watermelon',           img:'white-series/frozen-watermelon.webp',           price:18.99, puffs:'6,500', badge:'Bestseller',
      desc:'The purest watermelon experience — icy cold, crystal clear, and perfectly ripe. No additives, just fresh watermelon frozen solid. This White Series classic is the gold standard of fruit-ice vapes.',
      tags:['fruit','watermelon','ice'] },
    { id:'mint-ws',                     cat:'white-series', name:'Mint',                        img:'white-series/mint.webp',                        price:18.99, puffs:'6,500', badge:null,
      desc:'White Series Mint brings an extra level of smooth, glacial coolness. Fresh American peppermint vapor that cleanses and refreshes with every puff — an everyday essential for menthol lovers.',
      tags:['mint','ice'] },
    { id:'pineapple-whip',              cat:'white-series', name:'Pineapple Whip',              img:'white-series/pineapple-whip.webp',              price:18.99, puffs:'6,500', badge:'🔥 Hot',
      desc:'Tangy pineapple churned into a smooth, creamy whip — like a Dole Whip in vapor form. Sweet, tropical, and incredibly smooth. One of the most unique dessert-fruit hybrids in the White Series.',
      tags:['fruit','pineapple','cream','dessert'] },
    { id:'strawberry-kiwi-ice',         cat:'white-series', name:'Strawberry Kiwi Ice',         img:'white-series/strawberry-kiwi-ice.webp',         price:18.99, puffs:'6,500', badge:'Popular',
      desc:'Classic strawberry kiwi — a pairing as timeless as it is delicious — chilled to a perfect icy finish. Sweet ripe strawberries and tropical kiwi, frosted and ready to go.',
      tags:['fruit','strawberry','kiwi','ice'] },
    { id:'strawberry-lemon-grape',      cat:'white-series', name:'Strawberry Lemon Grape',      img:'white-series/strawberry-lemon-grape.webp',      price:18.99, puffs:'6,500', badge:null,
      desc:'A bold three-way fruit mashup — ripe strawberry, sharp lemon zest, and deep Concord grape — creates a complex, tart-sweet vaping experience unlike anything else in the White Series.',
      tags:['fruit','strawberry','lemon','grape'] },
    { id:'strawberry-watermelon-twist', cat:'white-series', name:'Strawberry Watermelon Twist', img:'white-series/strawberry-watermelon-twist.webp', price:18.99, puffs:'6,500', badge:null,
      desc:'Sweet ripe strawberries twisted together with fresh, juicy watermelon — a duo that\'s brighter than the sum of its parts. Smooth, fruity, and perfectly balanced. The definitive summer White Series flavor.',
      tags:['fruit','strawberry','watermelon'] },

    /* ── BLACK SERIES (20,000 puffs) ── */
    { id:'blueberry-cereal-donut-milk-bs', cat:'black-series', name:'Blueberry Cereal Donut Milk', img:'black-series/blueberry-cereal-donut-milk.webp', price:24.99, puffs:'20,000', badge:'Bestseller',
      desc:'The Black Series flagship flavor — layers of sweet blueberry cereal, glazed donut richness, and cold creamy milk in 20,000 puffs of American-made perfection. Dual Parallel Mesh Coil technology keeps every puff as good as the first.',
      tags:['dessert','cereal','blueberry','cream'] },
    { id:'blueberry-yogurt',            cat:'black-series', name:'Blueberry Yogurt',            img:'black-series/blueberry-yogurt.webp',            price:24.99, puffs:'20,000', badge:null,
      desc:'Creamy Greek-style yogurt swirled with ripe blueberries — tart, sweet, and refreshingly smooth. A sophisticated flavor pairing in the Black Series that hits differently with the Dual Parallel Mesh Coil.',
      tags:['dessert','blueberry','cream'] },
    { id:'butterbean',                  cat:'black-series', name:'Butterbean',                  img:'black-series/butterbean.webp',                  price:24.99, puffs:'20,000', badge:null,
      desc:'Smooth, sweet butterscotch-tinged vanilla cream — rich and velvety with a warm, buttery undertone. Butterbean is the Black Series wild card: unexpected, addictive, and deeply satisfying over 20,000 puffs.',
      tags:['dessert','vanilla','cream','butterscotch'] },
    { id:'cinnamon-funnel-cake-bs',     cat:'black-series', name:'Cinnamon Funnel Cake',       img:'black-series/cinnamon-funnel-cake.webp',       price:24.99, puffs:'20,000', badge:'🔥 Hot',
      desc:'Fairground-fresh funnel cake dusted with cinnamon sugar, elevated to 20,000 puffs in the Black Series. Always Active Boost Mode ensures maximum flavor intensity from inhale to exhale — the carnival never ends.',
      tags:['dessert','cinnamon','pastry'] },
    { id:'gold-tobacco',                cat:'black-series', name:'Gold Tobacco',                img:'black-series/gold-tobacco.webp',                price:24.99, puffs:'20,000', badge:null,
      desc:'Premium American gold-leaf tobacco — smooth, slightly sweet, and perfectly refined. Gold Tobacco in the Black Series is the choice for the sophisticated vaper who demands quality over 20,000 long, satisfying puffs.',
      tags:['tobacco'] },
    { id:'kentucky-tobacco',            cat:'black-series', name:'Kentucky Tobacco',            img:'black-series/kentucky-tobacco.webp',            price:24.99, puffs:'20,000', badge:null,
      desc:'Bold, full-bodied Kentucky tobacco — earthy, rich, and authentic. The most robust tobacco profile in the Fifty Bar lineup, delivering a genuine American tobacco experience across 20,000 puffs.',
      tags:['tobacco'] },
    { id:'milky-loops',                 cat:'black-series', name:'Milky Loops',                 img:'black-series/milky-loops.webp',                 price:24.99, puffs:'20,000', badge:'Popular',
      desc:'Your favorite rainbow cereal loops soaked in cold, sweet milk — captured in the Black Series for 20,000 puffs of nostalgic breakfast bliss. Sweet, creamy, and absolutely irresistible.',
      tags:['dessert','cereal','cream'] },
    { id:'raspberry-jam',               cat:'black-series', name:'Raspberry Jam',               img:'black-series/raspberry-jam.webp',               price:24.99, puffs:'20,000', badge:null,
      desc:'Sweet, slightly tart raspberry jam — thick, rich, and bursting with berry flavor. Smooth as a morning spread, complex as a gourmet vape. Twenty thousand puffs of one of America\'s most beloved flavors.',
      tags:['fruit','berry','raspberry'] },
    { id:'strawberry-cereal-donut-milk', cat:'black-series', name:'Strawberry Cereal Donut Milk', img:'black-series/strawberry-cereal-donut-milk.webp', price:24.99, puffs:'20,000', badge:null,
      desc:'Strawberry-infused cereal, glazed donut, and creamy milk — the fruity counterpart to the classic Blueberry version. Bright strawberry flavor threads through every layer for a sweeter, fruitier Black Series experience.',
      tags:['dessert','cereal','strawberry','cream'] },
    { id:'strawberry-super-strudel',    cat:'black-series', name:'Strawberry Super Strudel',   img:'black-series/strawberry-super-strudel.webp',   price:24.99, puffs:'20,000', badge:'Popular',
      desc:'Flaky pastry crust filled with sweet strawberry jam and a dusting of powdered sugar — the Black Series take on the ultimate breakfast pastry. Rich, fruity, and bakery-fresh across 20,000 puffs.',
      tags:['dessert','strawberry','pastry'] },
    { id:'vanilla-custard-bs',          cat:'black-series', name:'Vanilla Custard',             img:'black-series/vanilla-custard.webp',             price:24.99, puffs:'20,000', badge:'Bestseller',
      desc:'The all-time classic in Black Series format — rich, velvety vanilla custard over 20,000 puffs with Always Active Boost Mode. Every puff delivers the same indulgent creaminess. The standard by which all dessert vapes are measured.',
      tags:['dessert','vanilla','cream'] },

    /* ── FRUITIA × FIFTY BAR 20K ── */
    { id:'b-pop',                       cat:'fruitia', name:'B-Pop',             img:'fruitia/b-pop.webp',            price:24.99, puffs:'20,000', badge:'Popular',
      desc:'Fruitia\'s iconic B-Pop — sweet, explosive bubblegum-style candy with a bright tropical pop. In the 20K format with Fifty Bar\'s dual mesh coil, every puff is an American-made candy experience at maximum intensity.',
      tags:['candy','sweet','bubblegum'] },
    { id:'baja-burst',                  cat:'fruitia', name:'Baja Burst',        img:'fruitia/baja-burst.webp',       price:24.99, puffs:'20,000', badge:null,
      desc:'A tropical citrus blast inspired by the Baja coast — sweet, tangy, and refreshing. Fruitia\'s signature Baja Burst flavor gets the Fifty Bar 20K treatment: 20,000 puffs of pure American-made tropical energy.',
      tags:['fruit','citrus','tropical'] },
    { id:'blueberry-pound-cake',        cat:'fruitia', name:'Blueberry Pound Cake', img:'fruitia/blueberry-pound-cake.webp', price:24.99, puffs:'20,000', badge:null,
      desc:'Dense, buttery pound cake loaded with fresh blueberries — a Fruitia bakery masterpiece in 20K puff format. Rich dessert flavor with fruity brightness that Fruitia does better than anyone.',
      tags:['dessert','blueberry','pastry'] },
    { id:'bonker-berries',              cat:'fruitia', name:'Bonker Berries',     img:'fruitia/bonker-berries.webp',   price:24.99, puffs:'20,000', badge:null,
      desc:'Wild mixed berry chaos — strawberry, blueberry, and raspberry collide in Fruitia\'s signature Bonker Berries blend. Intensely fruity, slightly candy-sweet, and perfectly executed over 20,000 puffs.',
      tags:['fruit','berry','mixed'] },
    { id:'cookie-butter',               cat:'fruitia', name:'Cookie Butter',      img:'fruitia/cookie-butter.webp',    price:24.99, puffs:'20,000', badge:'🔥 Hot',
      desc:'Speculoos cookie butter — rich, spiced shortbread spread with notes of caramel and cinnamon. Fruitia\'s most indulgent flavor in the Fifty Bar 20K is a gourmet dessert experience built to American quality standards.',
      tags:['dessert','cookie','spice'] },
    { id:'hawaiian-punch-f',            cat:'fruitia', name:'Hawaiian Punch',     img:'fruitia/hawaiian-punch.webp',   price:24.99, puffs:'20,000', badge:'Bestseller',
      desc:'The legendary Hawaiian Punch fruit blend — tropical, sweet, and instantly recognizable — reimagined by Fruitia in the Fifty Bar 20K. Twenty thousand puffs of American-tropical goodness with Boost Mode always on.',
      tags:['fruit','tropical','punch'] },
    { id:'polar-ice',                   cat:'fruitia', name:'Polar Ice',          img:'fruitia/polar-ice.webp',        price:24.99, puffs:'20,000', badge:null,
      desc:'Sub-zero arctic menthol — the coldest vape in the Fruitia × Fifty Bar 20K lineup. Pure polar ice that hits immediately and lingers with a lasting cool exhale. For menthol lovers who want maximum frost.',
      tags:['ice','menthol','mint'] },
    { id:'sour-batch',                  cat:'fruitia', name:'Sour Batch',         img:'fruitia/sour-batch.webp',       price:24.99, puffs:'20,000', badge:'Popular',
      desc:'Mouth-puckering sour candy in a mixed-berry medley — Fruitia\'s famous Sour Batch in Fifty Bar 20K format. Sharp sour inhale, sweet candy finish. Twenty thousand puffs of sweet-and-sour American candy perfection.',
      tags:['candy','sour','berry'] },
    { id:'southern-tobacco',            cat:'fruitia', name:'Southern Tobacco',   img:'fruitia/southern-tobacco.webp', price:24.99, puffs:'20,000', badge:null,
      desc:'Smooth, Southern-style tobacco — warm and mellow with subtle sweetness. Fruitia\'s take on an American classic, now in 20K puff format with Dual Parallel Mesh Coil for consistent tobacco flavor to the last drop.',
      tags:['tobacco'] },
    { id:'spearmint',                   cat:'fruitia', name:'Spearmint',          img:'fruitia/spearmint.webp',        price:24.99, puffs:'20,000', badge:null,
      desc:'Cool, sweet spearmint — lighter and sweeter than peppermint with a smooth, lingering freshness. Fruitia\'s classic Spearmint in the 20K format is the everyday mint vape for those who prefer smooth over sharp.',
      tags:['mint'] },
    { id:'strawberry-beltz',            cat:'fruitia', name:'Strawberry Beltz',   img:'fruitia/strawberry-beltz.webp', price:24.99, puffs:'20,000', badge:null,
      desc:'Sweet strawberry candy belts — the chewable candy experience in vapor form. Bright strawberry with a sugary candy coating, built to Fruitia\'s exacting flavor standards and delivered over 20,000 Fifty Bar puffs.',
      tags:['candy','strawberry','sweet'] },
    { id:'swedish-fish',                cat:'fruitia', name:'Swedish Fish',        img:'fruitia/swedish-fish.webp',     price:24.99, puffs:'20,000', badge:'Popular',
      desc:'The iconic Swedish Fish candy — sweet, berry-forward, and unmistakably nostalgic. Fruitia nails it in the Fifty Bar 20K format. Twenty thousand puffs of America\'s favorite gummy candy in perfect vapor form.',
      tags:['candy','berry','sweet'] },

    /* ── HUMBLE × FIFTY BAR (6,500 puffs) ── */
    { id:'banana-funnel-cake',          cat:'humble', name:'Banana Funnel Cake',     img:'humble/banana-funnel-cake-1.webp',      price:18.99, puffs:'6,500', badge:null,
      desc:'Humble\'s beloved Banana Funnel Cake — ripe banana over warm, crispy fried funnel cake dusted with sugar. A uniquely American dessert mashup that Humble and Fifty Bar have perfected together.',
      tags:['dessert','banana','pastry'] },
    { id:'blue-razz-bubblegum',         cat:'humble', name:'Blue Razz Bubblegum',    img:'humble/blue-razz-bubblegum-1-1.webp',   price:18.99, puffs:'6,500', badge:'Popular',
      desc:'Humble\'s classic Blue Razz Bubblegum — tangy blue raspberry wrapped in sweet bubblegum candy. A two-flavor knockout in the Fifty Bar device, delivering 6,500 puffs of American candy-vape greatness.',
      tags:['candy','berry','bubblegum'] },
    { id:'blue-slush',                  cat:'humble', name:'Blue Slush',             img:'humble/blue-slush-1-1.webp',            price:18.99, puffs:'6,500', badge:null,
      desc:'Ice-cold blue raspberry slushie — the summer drink in vapor form. Humble\'s Blue Slush is refreshingly sharp and frosty, every single puff. Perfect for hot days and blue raspberry lovers everywhere.',
      tags:['candy','berry','ice'] },
    { id:'golden-mango',                cat:'humble', name:'Golden Mango',            img:'humble/golden-mango-1-1.webp',          price:18.99, puffs:'6,500', badge:null,
      desc:'Humble\'s Golden Mango — ripe, golden Ataulfo mango with a sweet, buttery richness. Less tart than typical mango flavors, more complex, and perfectly complemented by the Fifty Bar\'s smooth American vapor delivery.',
      tags:['fruit','mango','tropical'] },
    { id:'lemon-watermelon',            cat:'humble', name:'Lemon Watermelon',        img:'humble/lemon-watermelon-1-1.webp',      price:18.99, puffs:'6,500', badge:'🔥 Hot',
      desc:'Bright lemon zest meets sweet summer watermelon in this Humble × Fifty Bar standout. Tart-sweet, refreshing, and perfectly balanced — a flavor pairing that simply works every time.',
      tags:['fruit','lemon','watermelon'] },
    { id:'orange-mango-sherbet',        cat:'humble', name:'Orange Mango Sherbet',    img:'humble/orange-mango-sherbet-1-1.webp',  price:18.99, puffs:'6,500', badge:null,
      desc:'Creamy sherbet swirled with sweet orange and ripe mango — a frozen dessert experience in every puff. Humble\'s sherbet series meets Fifty Bar quality for a smooth, fruity, creamy blend.',
      tags:['fruit','dessert','orange','mango'] },
    { id:'strawberry-banana',           cat:'humble', name:'Strawberry Banana',       img:'humble/strawberry-banana-1-1.webp',     price:18.99, puffs:'6,500', badge:'Bestseller',
      desc:'Humble\'s iconic Strawberry Banana — the smoothie that started a movement. Sweet ripe strawberries blended with creamy banana, smooth as silk, satisfying every time. A Fifty Bar × Humble collab essential.',
      tags:['fruit','strawberry','banana','cream'] },
    { id:'sweet-mint',                  cat:'humble', name:'Sweet Mint',              img:'humble/sweet-mint-1-1.webp',            price:18.99, puffs:'6,500', badge:null,
      desc:'Humble\'s Sweet Mint — cooler than spearmint, sweeter than peppermint. A perfectly dialed-in mint experience for everyday use. Smooth, refreshing, and approachable — the everyday mint choice in the Humble × Fifty Bar collab.',
      tags:['mint'] },
    { id:'vanilla-tobacco',             cat:'humble', name:'Vanilla Tobacco',         img:'humble/vanilla-tobacco-1-1.webp',       price:18.99, puffs:'6,500', badge:null,
      desc:'Smooth American tobacco layered with sweet, creamy vanilla — Humble\'s sophisticated tobacco blend in the Fifty Bar device. Complex, warm, and endlessly satisfying for tobacco lovers seeking something extra.',
      tags:['tobacco','vanilla'] },
    { id:'watermelon-lychee',           cat:'humble', name:'Watermelon Lychee',       img:'humble/watermelon-lychee-1-1.webp',     price:18.99, puffs:'6,500', badge:null,
      desc:'Fresh summer watermelon meets delicately floral lychee — an exotic fruit pairing that works beautifully together. Humble\'s Watermelon Lychee is light, tropical, and endlessly refreshing.',
      tags:['fruit','watermelon','lychee'] },

    /* ── HIDDEN HILLS × FIFTY BAR (6,500 puffs) ── */
    { id:'hawaiian-nectar',             cat:'hidden-hills', name:'Hawaiian Nectar',         img:'hidden-hills/hawaiian-nectar.webp',      price:18.99, puffs:'6,500', badge:'Popular',
      desc:'Hidden Hills Club\'s Hawaiian Nectar — a tropical fruit blend of guava, papaya, and passion fruit, each note perfectly clear and vibrant. Sip the islands in every puff with the Fifty Bar 6,500-puff device.',
      tags:['fruit','tropical','guava'] },
    { id:'honeyberry-cream',            cat:'hidden-hills', name:'Honeyberry Cream',        img:'hidden-hills/honeyberry-cream.webp',     price:18.99, puffs:'6,500', badge:null,
      desc:'Sweet honeyed berries draped in smooth, rich cream — Hidden Hills Club\'s most indulgent fruit-dessert hybrid. Perfectly balanced between fruity freshness and dessert richness.',
      tags:['fruit','berry','cream','dessert'] },
    { id:'lava-blast',                  cat:'hidden-hills', name:'Lava Blast',              img:'hidden-hills/lava-blast.webp',           price:18.99, puffs:'6,500', badge:'🔥 Hot',
      desc:'Hidden Hills Club Lava Blast — an explosive tropical volcano of mango, passion fruit, and guava with a warm, fruity finish. One of the most distinctive and bold flavors in the entire Fifty Bar lineup.',
      tags:['fruit','tropical','mango'] },
    { id:'lemon-cake-dough',            cat:'hidden-hills', name:'Lemon Cake Dough',        img:'hidden-hills/lemon-cake-dough.webp',     price:18.99, puffs:'6,500', badge:null,
      desc:'Bright lemon zest baked into a soft, sweet cake dough — tart citrus meets warm pastry in this Hidden Hills Club signature. A unique bakery-citrus flavor experience with 6,500 puffs of quality American vapor.',
      tags:['dessert','lemon','pastry'] },
    { id:'pina-lush',                   cat:'hidden-hills', name:'Piña Lush',               img:'hidden-hills/pina-lush.webp',            price:18.99, puffs:'6,500', badge:null,
      desc:'Creamy piña colada — tropical pineapple and coconut cream blended to lush perfection by Hidden Hills Club. A vacation in every puff, delivered in the reliable Fifty Bar device.',
      tags:['fruit','pineapple','coconut','cream'] },
    { id:'pink-milk',                   cat:'hidden-hills', name:'Pink Milk',               img:'hidden-hills/pink-milk.webp',            price:18.99, puffs:'6,500', badge:null,
      desc:'Sweet strawberry-cereal milk — the pink milk left after a bowl of fruity cereal, elevated to a premium vapor experience. Light, sweet, and nostalgically comforting. Hidden Hills Club at its most playful.',
      tags:['dessert','strawberry','cream','cereal'] },
    { id:'pink-sour-straws',            cat:'hidden-hills', name:'Pink Sour Straws',        img:'hidden-hills/pink-sour-straws.webp',     price:18.99, puffs:'6,500', badge:'Popular',
      desc:'Iconic pink sour straw candy — that perfect sour-sweet punch of strawberry-lemon in sour candy form. Hidden Hills Club\'s signature candy vape, mouth-puckering and addictive across 6,500 American-made puffs.',
      tags:['candy','sour','strawberry'] },
    { id:'sour-peach-ringz',            cat:'hidden-hills', name:'Sour Peach Ringz',        img:'hidden-hills/sour-peach-ringz.webp',     price:18.99, puffs:'6,500', badge:null,
      desc:'Sugar-coated sour peach gummy rings — the candy aisle in vapor form. Sweet Georgia peach with a tart sour edge and a sugary candy coating. Hidden Hills Club\'s most fun, most shareable flavor.',
      tags:['candy','sour','peach'] },
    { id:'vanilla-bean-tobacco',        cat:'hidden-hills', name:'Vanilla Bean Tobacco',    img:'hidden-hills/vanilla-bean-tobacco.webp', price:18.99, puffs:'6,500', badge:null,
      desc:'Premium vanilla bean extract meets smooth American tobacco in Hidden Hills Club\'s most refined blend. Warm, sweet, and sophisticated — the choice for tobacco vapers who want a touch of luxury.',
      tags:['tobacco','vanilla'] },
    { id:'wazza-limon',                 cat:'hidden-hills', name:'Wazza Limon',             img:'hidden-hills/wazza-limon.webp',          price:18.99, puffs:'6,500', badge:null,
      desc:'A bold lemon-citrus candy explosion — bright, sharp, and intensely lemony. Wazza Limon from Hidden Hills Club hits hard with citrus candy flavor that lasts across all 6,500 puffs.',
      tags:['candy','lemon','citrus'] },
    { id:'yeti-mint',                   cat:'hidden-hills', name:'Yeti Mint',               img:'hidden-hills/yeti-mint.webp',            price:18.99, puffs:'6,500', badge:null,
      desc:'Yeti-grade arctic mint — the coldest, most intense menthol experience in the Hidden Hills × Fifty Bar lineup. If you want maximum freeze, Yeti Mint is the one. Extreme cool, American made.',
      tags:['mint','ice','menthol'] },

    /* ── MIDNIGHT SERIES (20,000 puffs) ── */
    { id:'iced-strawberry-pear',        cat:'midnight-series', name:'Iced Strawberry Pear',    img:'midnight-series/iced-strawberry-pear.png',    price:24.99, puffs:'20,000', badge:'New',
      desc:'Sweet, ripe strawberries blended with crisp, juicy pear — then frozen to an icy perfection. The Fifty Bar Midnight Series Iced Strawberry Pear delivers 20,000 puffs of refreshing fruit-ice flavor with Always Active Boost Mode for maximum intensity. Dual Parallel Mesh Coil technology ensures smooth, consistent vapor from the first puff to the last.',
      tags:['fruit','strawberry','pear','ice'] },
    { id:'iced-green-rancher',          cat:'midnight-series', name:'Iced Green Rancher',      img:'midnight-series/iced-green-rancher.png',      price:24.99, puffs:'20,000', badge:'New',
      desc:'Inspired by the classic green apple hard candy, Iced Green Rancher translates that sharp, sweet-tart apple flavor into an icy, refreshing vape experience. Twenty thousand puffs of nostalgia, upgraded with Dual Parallel Mesh Coil technology and 3-Level Adjustable Airflow for your perfect draw.',
      tags:['candy','apple','ice'] },
    { id:'iced-blue-rancher',           cat:'midnight-series', name:'Iced Blue Rancher',       img:'midnight-series/iced-blue-rancher.png',       price:24.99, puffs:'20,000', badge:'New',
      desc:'The blue raspberry take on a hard candy classic — Iced Blue Rancher delivers the iconic blue candy flavor with a deep freeze finish. Bold, sweet-tart blue raspberry meets arctic ice in the Fifty Bar Midnight Series. 20K puffs with Always Active Boost Mode means every hit is as vibrant as the last.',
      tags:['candy','berry','ice'] },
    { id:'sour-strawberry-melon',       cat:'midnight-series', name:'Sour Strawberry Melon',   img:'midnight-series/sour-strawberry-melon.png',   price:24.99, puffs:'20,000', badge:'New',
      desc:'A mouth-puckering sour candy twist on two fruit classics — sweet strawberry and fresh watermelon collide with a sharp sour edge. The Midnight Series Sour Strawberry Melon is complex, tart, and irresistibly refreshing. Experience 20,000 puffs with Grade A 900mAh rechargeable battery and visual e-liquid display.',
      tags:['fruit','sour','strawberry','watermelon'] },
    { id:'orange-mint',                 cat:'midnight-series', name:'Orange Mint',             img:'midnight-series/orange-mint.png',             price:24.99, puffs:'20,000', badge:'New',
      desc:'Fresh-squeezed citrus orange meets clean, cool spearmint in an unexpected and brilliantly executed pairing. Bright orange on the inhale, refreshing mint on the exhale — Midnight Series Orange Mint is a flavor combination that shouldn\'t work as well as it does. Delivered over 20,000 puffs with 3-Level Adjustable Airflow.',
      tags:['fruit','citrus','mint'] },
    { id:'limoncello',                  cat:'midnight-series', name:'Limoncello',              img:'midnight-series/limoncello.png',              price:24.99, puffs:'20,000', badge:'New',
      desc:'Italian Limoncello captured in American-made vapor — bright, zesty lemon concentrate with a sweet syrupy finish and a cool exhale. The Fifty Bar Midnight Series Limoncello is the most sophisticated citrus vape in the lineup. Twenty thousand puffs of pure citrus luxury with Dual Parallel Mesh Coil and Always Active Boost Mode.',
      tags:['citrus','lemon','sweet'] },
    { id:'frozen-peach-lime-razz',      cat:'midnight-series', name:'Frozen Peach Lime Razz',  img:'midnight-series/frozen-peach-lime-razz.png',  price:24.99, puffs:'20,000', badge:'New',
      desc:'A frozen triple-fruit masterpiece — sweet Georgia peach, tart lime, and tangy blue raspberry layered together and blasted with arctic ice. Frozen Peach Lime Razz is the Midnight Series at its most adventurous — complex, bold, and deeply refreshing. 20,000 puffs with 900mAh Grade A battery and visual display.',
      tags:['fruit','peach','lime','raspberry','ice'] },
    { id:'frozen-orange-pom',           cat:'midnight-series', name:'Frozen Orange Pom',       img:'midnight-series/frozen-orange-pom.png',       price:24.99, puffs:'20,000', badge:'New',
      desc:'Sun-ripened orange meets tart pomegranate, both flash-frozen for a powerful, refreshing combination. Frozen Orange Pom is one of the most unique fruit pairings in the entire Fifty Bar Midnight Series — vibrant, complex, and perfectly icy across 20,000 American-made puffs with Always Active Boost Mode.',
      tags:['fruit','orange','pomegranate','ice'] },
    { id:'banana-fresca',               cat:'midnight-series', name:'Banana Fresca',           img:'midnight-series/banana-fresca.png',           price:24.99, puffs:'20,000', badge:'New',
      desc:'Ripe, tropical banana with a light sparkling fresca finish — fruity, smooth, and refreshing. Banana Fresca captures the essence of a fresh banana agua fresca and translates it into a smooth, creamy vape experience. Twenty thousand puffs of American-crafted tropical flavor with 3-Level Adjustable Airflow and Dual Parallel Mesh Coil.',
      tags:['fruit','banana','tropical'] },
  ],
};

/* ── Product lookup helpers ── */
FBV.getById   = id  => FBV.products.find(p => p.id === id);
FBV.getByCat  = cat => FBV.products.filter(p => p.cat === cat);
FBV.getCat    = id  => FBV.categories.find(c => c.id === id);
FBV.getSpec   = cat => {
  const puffs = FBV.getCat(cat)?.puffs;
  return puffs === '20,000' ? FBV.specs.twentyk : FBV.specs.standard;
};
